name: Build JAR for marquee-core
on:
  push:
    tags:
      - "core-v*"
      - "!core-v*-SNAPSHOT"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-core:
    name: Build JAR for marquee-core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: ""
          draft: true
