name: Build
on:
  push:
    tags:
      - core-v*.*.*!-
  workflow_dispatch:
jobs:
  build:
    name: Build JAR for marquee-core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build with Gradle
        run: ./gradlew :marquee-core:jar
      - name: Upload JAR
        uses: actions/upload-artifact@v7
        with:
          path: marquee-core/build/libs/*.jar
          archive: true